[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pytomato"
version = "0.4.5"
description = "Topological Mode Analysis Tool for fast, persistent, density-based clustering."
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "numba",
    "numpy",
    "scipy",
    "scikit-learn",
    "pynndescent",
    "matplotlib",
]

license = { file = "LICENSE" }

[project.urls]
Homepage = "https://github.com/kc-howe/tomato"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]